/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pongmult;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author c3rea
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
     private JFrame jframe;
     
      public Login() {
        initComponents();
    }

    // Constructor that accepts a Welcome frame
    public Login(JFrame jframe) {
        this.jframe = jframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_gamertag = new javax.swing.JLabel();
        txt_gamertag = new javax.swing.JTextField();
        lbl_loginM = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();
        pwd_L = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        btn_backL1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_gamertag.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_gamertag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gamertag.setText("Gamertag:");

        txt_gamertag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gamertagActionPerformed(evt);
            }
        });

        lbl_loginM.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbl_loginM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loginM.setText(" Login to play Pong");

        lbl_pass.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pass.setText("Password:");

        btn_Login.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        btn_backL1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_backL1.setText("Back");
        btn_backL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backL1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lbl_loginM, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_gamertag, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_gamertag, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(pwd_L)
                            .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_loginM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_gamertag, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gamertag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_L, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_backL1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_gamertagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gamertagActionPerformed
    }//GEN-LAST:event_txt_gamertagActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
try {
    boolean isAuthenticated;
    String GamerTag = txt_gamertag.getText(); // Get the gamer tag from the text field
    char[] passchars = pwd_L.getPassword(); // Get the password from the password field
    String password = new String(passchars); // Convert the password character array to a string

    // Look up the remote object in the RMI registry
    RegisterInterface R1 = (RegisterInterface) Naming.lookup("rmi://192.168.215.220:1099/RegisterInterface");

    // Call the remote Login method
    isAuthenticated = R1.Login(GamerTag, password);

    if (isAuthenticated) {
        JOptionPane.showMessageDialog(this, "Login successful!"); // Notify user of successful login
        // Proceed to the next screen or functionality
           // Create an instance of Test and make it visible
    TestLogin TestFrame = new TestLogin(this);
    TestFrame.setVisible(true);

    // Dispose of the current Welcome frame
    this.dispose(); 
    } else {
        JOptionPane.showMessageDialog(this, "Invalid GamerTag or Password", "Login Failed", JOptionPane.ERROR_MESSAGE); // Notify user of failure
    }
} catch (NotBoundException | MalformedURLException | RemoteException ex) {
    // Handle potential exceptions
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
}    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_backL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backL1ActionPerformed
        // Create an instance of Welcome and make it visible
        Welcome welcomeFrame = new Welcome(this);
        welcomeFrame.setVisible(true);

        // Dispose of the current Register frame
        this.dispose();
    }//GEN-LAST:event_btn_backL1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_backL1;
    private javax.swing.JLabel lbl_gamertag;
    private javax.swing.JLabel lbl_loginM;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JPasswordField pwd_L;
    private javax.swing.JTextField txt_gamertag;
    // End of variables declaration//GEN-END:variables
}
