/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pongmult;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author c3rea
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    private Welcome welcomeFrame;

    // Constructor that accepts a Welcome frame
    public Register(Welcome welcomeFrame) {
        this.welcomeFrame = welcomeFrame;
        initComponents();
    }

    // The existing constructor if needed
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_tag = new javax.swing.JLabel();
        lbl_Fname = new javax.swing.JLabel();
        lbl_Lname = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_Fname = new javax.swing.JTextField();
        txt_tag = new javax.swing.JTextField();
        txt_Lname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        lbl_password = new javax.swing.JLabel();
        pwd_R = new javax.swing.JPasswordField();
        btn_Lreidrect = new javax.swing.JButton();
        btn_Lreidrect.setVisible(false);

        btn_backL1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        lbl_title.setBackground(new java.awt.Color(204, 255, 204));
        lbl_title.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbl_title.setText("Register your PingPong Account");

        lbl_tag.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_tag.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tag.setText("GamerTag:");

        lbl_Fname.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_Fname.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Fname.setText("First Name:");

        lbl_Lname.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_Lname.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Lname.setText("Last Name:");

        lbl_email.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("Email");

        txt_Fname.setBackground(new java.awt.Color(255, 204, 204));

        txt_tag.setBackground(new java.awt.Color(255, 204, 204));
        txt_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tagActionPerformed(evt);
            }
        });

        txt_Lname.setBackground(new java.awt.Color(255, 204, 204));

        txt_email.setBackground(new java.awt.Color(255, 204, 204));

        btn_create.setBackground(new java.awt.Color(204, 204, 255));
        btn_create.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_create.setForeground(new java.awt.Color(0, 51, 51));
        btn_create.setText("Create Account");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        lbl_password.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setText("Password:");

        pwd_R.setBackground(new java.awt.Color(255, 204, 204));

        btn_Lreidrect.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_Lreidrect.setText("Login");
        btn_Lreidrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LreidrectActionPerformed(evt);
            }
        });

        btn_backL1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_backL1.setText("Back");
        btn_backL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backL1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_tag, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tag, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(pwd_R))))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Lreidrect, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(btn_backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tag)
                    .addComponent(txt_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fname)
                    .addComponent(txt_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Lname)
                    .addComponent(txt_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(pwd_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btn_create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btn_Lreidrect)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(btn_backL1)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tagActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        try {
            
            String GamerTag = txt_tag.getText();
            String Fname = txt_Fname.getText();
            String Lname = txt_Lname.getText();
            String Email = txt_email.getText(); 
            char[] passwordChars = pwd_R.getPassword(); ///password field returns array of chars
            String Plainpassword = new String(passwordChars);// create string from chaaracter arrays
            
           if (GamerTag.isEmpty() || Fname.isEmpty() || Lname.isEmpty() || Email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields must be filled out", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
          // Look up the remote object in the RMI registry
            RegisterInterface R1 = (RegisterInterface) Naming.lookup("rmi://192.168.215.220:1099/RegisterInterface");
            String result = R1.insert(GamerTag, Fname, Lname, Email,Plainpassword);
            JOptionPane.showMessageDialog(null, result,"success",JOptionPane.INFORMATION_MESSAGE);
            btn_Lreidrect.setVisible(true);

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e,"error",JOptionPane.ERROR_MESSAGE);           
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_LreidrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LreidrectActionPerformed
// Create an instance of Login and make it visible
    Login loginFrame = new Login(this);
    loginFrame.setVisible(true);

    // Dispose of the current Welcome frame
    this.dispose();        
    }//GEN-LAST:event_btn_LreidrectActionPerformed

    private void btn_backL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backL1ActionPerformed
// Create an instance of Welcome and make it visible
    Welcome welcomeFrame = new Welcome(this);
    welcomeFrame.setVisible(true);

    // Dispose of the current Register frame
    this.dispose();   
    }//GEN-LAST:event_btn_backL1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Lreidrect;
    private javax.swing.JButton btn_backL1;
    private javax.swing.JButton btn_create;
    private javax.swing.JLabel lbl_Fname;
    private javax.swing.JLabel lbl_Lname;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_tag;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPasswordField pwd_R;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Lname;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_tag;
    // End of variables declaration//GEN-END:variables
}
